### ISSUE TITLE
Decide on Frontend UI Framework

### ISSUE THREAD

**Issue by scottbot95** [real-fake-spaceshop/real-fake-spaceshop#40]
We need to pick a Frontend UI framework. Possible options include :
- [Semantic UI](https://semantic-ui.com/)
- [React Bootstrap](https://react-bootstrap.github.io)
- [Material UI](https://material-ui.com)

**Comment by Badbradsback** [comment]
I think we should try Material UI

**Comment by scottbot95** [comment]
I think both Material and Semantic UI look good. I do have a slight preference towards Material UI, but we could use either honestly.

**Comment by dboicourt** [comment]
Material UI looks pretty solid, lets go for it
